/* Site-plan save / export / import (params only).
 *
 * The planner can hold several simulated sites, but they live only in memory.
 * This module serializes the *parameters* of a site list to/from a small,
 * versioned, self-describing JSON "site plan" — for persistence (localStorage),
 * for export to a single shareable file, and for re-import on another device.
 *
 * Deliberately params-only: coverage rasters are large and cheap to recompute
 * (see src/persist.ts), so we never serialize the dBm grids. On load/import the
 * caller recreates sites from params and recomputes coverage on demand.
 *
 * Pure and DOM-free so it is unit-testable and safe to run anywhere. The
 * versioned envelope is forward-compatible: an older build reading a newer
 * "version" rejects loudly; a newer build reading an older one still accepts it.
 */

import type { Site, SplatParams } from './types';

export const SITE_PLAN_FORMAT = 'meshtastic-site-plan';
export const SITE_PLAN_VERSION = 1;

/** A single site's persisted form: its name plus the full parameter set. */
export interface SitePlanSite {
  name: string;
  params: SplatParams;
}

/** The versioned envelope written to disk / localStorage. */
export interface SitePlan {
  format: typeof SITE_PLAN_FORMAT;
  version: number;
  /** ISO timestamp; informational only. */
  exportedAt: string;
  /** Tool that produced it; informational only. */
  generator: string;
  /** User labelling for the study; informational only. */
  projectName: string;
  sites: SitePlanSite[];
  /** Global display prefs so a restored study looks the same. */
  display: { overlayStyle?: 'heatmap' | 'contours'; colorScale?: string };
}

const GENERATOR = 'meshtastic-site-planner';

/** Build a serializable plan from the in-memory site list (params only). */
export function exportSitePlan(sites: Site[], opts: { projectName?: string } = {}): SitePlan {
  const plan: SitePlan = {
    format: SITE_PLAN_FORMAT,
    version: SITE_PLAN_VERSION,
    exportedAt: new Date().toISOString(),
    generator: GENERATOR,
    projectName: opts.projectName ?? '',
    sites: sites.map((s) => ({ name: s.params.transmitter.name, params: s.params })),
    display: {},
  };
  return plan;
}

/** Pretty-printed JSON text of a plan (for the download / import flow). */
export function serializeSitePlan(plan: SitePlan): string {
  return JSON.stringify(plan, null, 2);
}

/** True if the object looks like a plan we can read (correct format/version). */
export function isSupportedSitePlan(value: unknown): value is SitePlan {
  if (!value || typeof value !== 'object') return false;
  const v = value as Record<string, unknown>;
  if (v.format !== SITE_PLAN_FORMAT) return false;
  if (typeof v.version !== 'number' || v.version > SITE_PLAN_VERSION) return false;
  if (!Array.isArray(v.sites)) return false;
  return true;
}

/** Parse + validate a plan from JSON text. Throws a clear Error on any problem,
 * so the import UI can show a helpful message instead of failing silently. */
export function parseSitePlan(text: string): SitePlan {
  if (!text || typeof text !== 'string') throw new Error('Empty file');
  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch {
    throw new Error('Not valid JSON');
  }
  if (!isSupportedSitePlan(parsed)) {
    throw new Error('Unrecognized or unsupported site-plan file (wrong format or newer version)');
  }
  // Light per-site sanity: each entry must at least carry a params object whose
  // transmitter section can be read. Clean out anything malformed so a partial
  // import still succeeds.
  parsed.sites = parsed.sites.filter(
    (s) => s && typeof s === 'object' && (s as SitePlanSite).params?.transmitter
  );
  return parsed;
}

/** Rehydrate persisted sites into the in-memory shape, preserving caller-
 * supplied ids (the old UUIDs are not persisted; fresh ones are generated by
 * the store on import). */
export function rehydrateSites(plan: SitePlan): SitePlanSite[] {
  return plan.sites;
}
